import React from 'react'

const About = () => {
  return (
    <div className="min-h-screen bg-white px-6 py-12 flex flex-col items-center">
      <div className="max-w-3xl text-center">
        <h1 className="text-4xl md:text-5xl font-bold mb-6 text-blue-700">
          About Us
        </h1>
        <p className="text-lg text-gray-700 mb-6">
          Welcome to <span className="font-semibold">Get Me A Chai</span> — a project which is a part of Sigma Web Development course by Code With Harry 
        </p>

        <h2 className="text-2xl font-semibold mt-10 mb-4 text-blue-600">
          Here is What I Learned In This Course 
        </h2>
        <ul className="text-left text-gray-700 list-disc list-inside space-y-2">
         
          <li>⚡ HTML </li>
          <li>🚀 CSS</li>
          <li>⚡ JavaScript</li>
          <li>🚀 React</li>
          <li>⚡ Express</li>
          <li>🚀 MongoDB</li>
          <li>⚡ Next.Js</li>
          
        </ul>

      </div>
    </div>
  );
};

export default About


export const metadata = {
  title: "About - Get Me A Chai",
  description: "Generated by create next app",
};
