import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import SessionWrapper from "@/components/SessionWrapper";
import Script from "next/script";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Get Me A Chai",
  description: "Generated by create next app",
   icons: [
    { rel: "icon", url: "/favicon.ico" },
    { rel: "icon", type: "image/svg+xml", url: "/favicon.svg" },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >

        <SessionWrapper>
          <Script src="https://cdn.lordicon.com/lordicon.js" strategy="afterInteractive" />

          <div className="min-h-screen flex flex-col  font-mono ">

            <div className="sticky top-0 z-10">

            <Navbar />
            </div>
          
            {children}
            <Footer />



          </div>
          

        </SessionWrapper>
      </body>
    </html>
  );
}

