import Dashboard from '@/components/Dashboard'
import React from 'react'

const Updatedashboard = () => {
  return (
    <div>
      <Dashboard/>
    </div>
  )
}

export default Updatedashboard


export const metadata = {
  title: "Update Dashboard - Get Me A Chai",
  description: "Generated by create next app",
};
